name: balanca_digital
description: Aplicação CLI para gestão de balanças e pesagens usando Firebase + MySQL (mysql_client).
version: 0.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mysql_client: ^0.0.27
  http: ^1.2.0